### ISSUE TITLE
Instructor Feedback - Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [TanwiSharma54/Cookbook#1]
What a fun project idea!

- [x] Be sure you include edit and delete capability, as those are required for the project.
- [x] One of the screens had a recipe image - is that part of the mvp? Is it represented the user stories?
- [x] timelog/weekly reflection is missing or did I overlook it?

**Comment by TanwiSharma54** [comment]
1> Yes, I will include edit and delete capability.

2> All Recipes page is a part of the mvp.
3> Added timelog/weekly reflection
https://github.com/TanwiSharma54/Cookbook/blob/Adding_google_login_api/DesignDocuments/WeeklyReflection.md
