### ISSUE TITLE
Dave's Week 6 Feedback

### ISSUE THREAD

**Issue by DQueiser** [TanwiSharma54/Cookbook#2]
# Design/Code Review 1

### Reviewer: Dave Queiser

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|The Problem Statement was very readable and easy to understand. The application it presented looks very interesting, and I will be keen to see the final version.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |The activity diagram was outstanding, and made me wish I had done as well with my own. Also, very clear screen designs that laid out just what the final app will look like.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|All the requirements for the database were present; the database layout itself looked clean and organized.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.|I saw no redundant code during the review. I think it will be a very interesting app when it is complete, and I'm looking forward to seeing the final version.

**Comment by pawaitemadisoncollege** [comment]
@DQueiser Can you fix up the formatting here? This should show as a "pretty" table. Let me know if you need help!

**Comment by DQueiser** [comment]
> @DQueiser Can you fix up the formatting here? This should show as a "pretty" table. Let me know if you need help!

Take #3 seems to have done the job. I just need to be careful how I edit my .md documents.
