### ISSUE TITLE
Checkpoint 2 - Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [TanwiSharma54/Cookbook#3]
- [x] Remember to complete any recommendation in the issues on your repository and close issues once all items are complete
- [x] Timelog/journal are missing?
- [x] Update project plan formatting for better readability
- [x] Update readme.md technology section for better readability
- [x] Let me know when your project is ready for a checkpoint 2 review (should have Hibernate implemented in at least one dao and unit tested), and I'll re-review.

Remember work is accepted up to 1 week late.

**Comment by TanwiSharma54** [comment]
1> Checked
2> updated timelog: https://github.com/TanwiSharma54/Cookbook/blob/Adding_google_login_api/DesignDocuments/TimeLog.md
3> updated project plan format:
https://github.com/TanwiSharma54/Cookbook/blob/Adding_google_login_api/DesignDocuments/ProjectPlan.md

4> updated Readme.md
https://github.com/TanwiSharma54/Cookbook/blob/Adding_google_login_api/README.md
