### ISSUE TITLE
Instructor feedback - Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [TanwiSharma54/Cookbook#5]
- [x] Your weekly reflection mentions multiple daos and unit tests. In checking both branches, I only see the GoogleApiDao, can you point me to the hibernate daos that you mention?
- [x] Database designed and created? Is the erd somewhere? 
- [x] Is the weekly reflection all your work? It looks familiar?

**Comment by TanwiSharma54** [comment]
1> Fixed:- 
https://github.com/TanwiSharma54/Cookbook/tree/Adding_google_login_api/src/main/java/edu/matc/persistence
2> https://github.com/TanwiSharma54/Cookbook/blob/Adding_google_login_api/DesignDocuments/Many_To_Many_ERDiagram.png

3> Actually, I've coppied from Dave for format and i forgot to change the content inside. Now I've Changed/fixed.
https://github.com/TanwiSharma54/Cookbook/blob/Adding_google_login_api/DesignDocuments/WeeklyReflection.md

**Comment by pawaitemadisoncollege** [comment]
Good morning.  

- [ ] What about delete, update and getAll functionality on the Dao? They are commented out? Not working for some reason? 
- [ ] ERD is missing a role table, ingredients?
